; Project PlatformIO tối giản cho ESP32-S3
; Chức năng:
; - Phát WiFi AP trước
; - Hỗ trợ Ethernet W5500 qua WebServer_ESP32_SC_W5500
; - Điều khiển LED ma trận HUB75 bằng ESP32-HUB75-MatrixPanel-I2S-DMA

[platformio]
default_envs = esp32-s3-devkit

[env:esp32-s3-devkit]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
; board_build.partitions = partitions.csv   ; dùng partition mặc định của board
build_flags =
  -Iincludes
  -DDISABLE_SPEECH
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
board_build.filesystem = littlefs

lib_deps =
  mrfaptastic/ESP32 HUB75 LED MATRIX PANEL DMA Display
  khoih-prog/WebServer_ESP32_SC_W5500
  bblanchon/ArduinoJson
  adafruit/Adafruit GFX Library


